import "./globals.css";
import { AuthProvider } from "../context/auth-context";
import { AuditProvider } from "../context/audit-context"; // Import AuditProvider
import { TenantProvider } from "../context/tenant-context"; // Import TenantProvider
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AuditProvider>
            <TenantProvider>
              {children}
              <ToastContainer position="top-right" autoClose={3000} />
            </TenantProvider>
          </AuditProvider>
        </AuthProvider>
      </body>
    </html>
  );
}